env:
  global:
  - secure: YKC3l+tXaW/THdghHO0iSAewLahUjL/XUGC3gOSYCc48fC8Vz3w8tj2BRQ1/QZXQLjkA2h4ubjm0yqCJwcbj5h6b8DZZF/E1uSQZRsqhG7RHhgeMh2DBK8gZkMwPzXNZjLAO2wJeg40WSHqGypUd28jeCxgAjwC3Cd1tIdIyxj8Opp5908Kwyw2FyyenIf9RjrobQrD5B9YZSnrGnW3md+Ib1S1z1Zq0w8SHZ+a87pN+4t8TG4+Xz7c7kOy1gCCBIkB8loRY+y3qCDpmILZ5rxIAA0C0NmVdPAycMbBTeVrdEBOWw0dkYrxI0XsFNQxxgjAbNeIczRteqaZX3gbo8xbLrEVQkzTKp7hHMtrkfGEO2D41eUhq6hQuYaI5AASSbF7l7sQWz5/qo/LOVMi4+3nDHbYna0A8Yr7/bLkaDDuPwlsTVxmI56jwGgON6urTOZq+p+lHT33uN71X7nkTnNaIaJLKMSK2owSYYGMLcNf3S8uhNXTKlFTMLdKy5UeZX/GhLBZcJeNx9SPC6yXAnlUKz0qsWwfAryPZdQOUuTikbs30umUlHO2gMS8WgayqUMdGw4L3vvxfDHM5GYEDgCs7/R/iutMPU5cqhXnUHz8CeFbgf93dfRWPaj3SzMJKRZ8cndFYe31TogLh5LeCLJhGkQEGdDNs4szWNWTSXws=
  - secure: h/H48/nDC9Fp12BoVqniG5dcrD0ozKGl2M9quJoVxygtNufv52YR+1hhfPlw87Yw2xt1FMkrHYdkMkpfchPnowQlf61XVd1N+AxxU+kmrHPD0awTL7+fBDPxckNxOXOJMpdsm53xkdi3v/bp8S6LYtw1AVCTvd7XEPn6aWQorveDCkKZXDbR46toMqKQZKy7wUMxjwtI8ok7Mo+HmA8nmWBYzNzl/sm+UPoqHIMqPxwumaqo6lkdWg9x/R7AN3AmOlth9keBlNoZFeJETM3n4tKn38ZxcW2zgawB1Dvf/N5NS2d6jzzWQthV267s9evc/5Piwi+FKCJ2XQso4j8gUNqG0ofPIht33sbyfHx7GovpMhxOwUYfg+yO0RdbslkNeo0SRWbzq6HpkLqXISnT1EPjBiX9mu8QDF1A092qFhz3aT8Dr1pmN7eM+wlC13mk1FyHz2t+XZSmUAFVQwRHpYkJ7puCq1HvaNuS87XlvQu3DdEadiTtElE1E+Ndw0kgsztUo0zbQRMsTBf6s4nw7gn7BKzoQssT5y19zPOG7ciR2oULRFKZwzzUFv5Gm/EW0R/Wf/8S1lLgLP/hTH19qyKHVU1XA53iilfFR13w+iG3naetjTVjIleD08KQ5W5Inq1wl5TGT40lWS7zqKzULLsEmjmsPiivMnF9jQi/iYc=
branches:
  only:
  - master
sudo: required
addons:
  apt:
    packages:
    - sshpass
language: generic
before_install:
- openssl aes-256-cbc -K $encrypted_dfdcfd5172af_key -iv $encrypted_dfdcfd5172af_iv -in deploy_key.enc -out ./deploy_key -d
after_success:
- export SSHPASS=$DEPLOY_PASS
deploy:
  provider: script
  skip_cleanup: true
  script: chmod 600 deploy_key && sshpass -e ssh -o StrictHostKeyChecking=no -i ./deploy_key root@$HOST_IP 'cd /home/some/dir ; exec "$SHELL" && /uks2020/deploy.sh'
  on:
    branch: master
