# Generated by Django 3.1.6 on 2021-04-06 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_repository_collaborators'),
        ('labels', '0002_auto_20210321_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='repository',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='repository.repository'),
            preserve_default=False,
        ),
    ]
