# Generated by Django 3.1.6 on 2021-03-09 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0001_initial'),
        ('issues', '0002_auto_20210307_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='milestones.milestone'),
        ),
    ]
