# Generated by Django 3.1.6 on 2021-02-15 21:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_branch_last_commit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commit',
            name='author',
        ),
        migrations.AddField(
            model_name='commit',
            name='author_email',
            field=models.CharField(default=django.utils.timezone.now, max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commit',
            name='author_name',
            field=models.CharField(default='Lazar', max_length=1024),
            preserve_default=False,
        ),
    ]
