# Generated by Django 3.1.6 on 2021-02-17 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20210215_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='private',
            new_name='is_private',
        ),
    ]
