# Generated by Django 3.1.6 on 2021-02-23 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_auto_20210217_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='readme',
            field=models.TextField(default=''),
        ),
    ]
